/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef APP_NAME_HELLO_WORLD_HPP_
#define APP_NAME_HELLO_WORLD_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0_1 {
namespace APP_NAME {

class HelloWorld {
public:
    virtual ~HelloWorld() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* HelloWorld::getInterface() {
    return ("APP_NAME.HelloWorld");
}

CommonAPI::Version HelloWorld::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace APP_NAME
} // namespace v0_1

namespace CommonAPI {
}

#endif // APP_NAME_HELLO_WORLD_HPP_
