/*
 * Copyright (C) 2016-2017 Neusoft, Inc.
 * All Rights Reserved.
 *
 * The following programs are the sole property of Neusoft Inc.,
 * and contain its proprietary and confidential information.
 */
#ifndef AMA_POWERTYPES_H_
#define AMA_POWERTYPES_H_

/*define power manager controller singal*/
enum ama_PowerSignal_e{
    E_PM_ACC_ON_POWER_ON,
    E_PM_ACC_ON_POWER_OFF,
    E_PM_ACC_OFF,
    E_PM_POWER_ON,
    E_PM_POWER_OFF,
    E_PM_POWER_OFF_AWAKE,
    E_PM_SCREEN_ON,
    E_PM_SCREEN_OFF,
    E_PM_SCREEN_OFF_AWAKE,
    E_PM_IGN_NOT_COME,
    E_PM_IGN_COME,      //10
    E_PM_SOC_TEMP_HIGH,
    E_PM_SOC_TEMP_NORMAL,
    E_PM_SOC_VOLTAGE_HIGH,
    E_PM_SOC_VOLTAGE_NORMAL,
    E_PM_SOC_VOLTAGE_LOW,
    E_SCR_TEMP_HIGH_90,
    E_SCR_TEMP_HIGH_90_95,
    E_SCR_TEMP_HIGH_95_100,
    E_SCR_TEMP_HIGH_100,
    E_APP_SCREEN_AWAKE_ON,  //20
    E_APP_SCREEN_AWAKE_OFF,
    E_APP_POWER_AWAKE_ON,
    E_APP_POWER_AWAKE_OFF,
    E_APP_ABNORMAL_AWAKE_ON,
    E_APP_ABNORMAL_AWAKE_OFF,
    E_APP_SET_GOODBYE,
    E_RSE_POWER_ON,
    E_RSE_POWER_OFF,
    E_RSE_SCREEN_ON,
    E_RSE_SCREEN_OFF ,      //30
    E_RSE_TIMER_ENABLE,
    E_RSE_TIMER_DISABLE,
    E_BOOT_WELCOME_PLAY_START,
    E_BOOT_WELCOME_PLAY_OVER,
    E_BOOT_FIRST_APP_READY,
    E_PSIG_DEF_MAX
};

#define POWER_ACC_FLAG      (0x10000000)
#define POWER_NORMAL_FLAG   (0x01000000)
#define POWER_POWER_FLAG    (0x00100000)
#define POWER_SCR_FLAG      (0x00010000)
#define POWER_AWAKE_FLAG    (0x00001000)
#define POWER_EVENT_FLAG    (0x00000100)
#define POWER_LEVEL_FLAG    (0x000000F0)

#define IS_POWER_EVENT(powerSta)        ((powerSta)&POWER_EVENT_FLAG)

enum ama_PowerState_e{
    E_PS_IG_COME_NOTIFY = 0x00000100,
    E_PS_IG_NOT_COME_NOTIFY = 0x00000101,
    E_PS_ACCOFF = 0x01000090,
    E_PS_POWER_INIT = 0x01000001,
    E_PS_WELCOME_MODE = 0x01000092,
    E_PS_OPENING_MODE = 0x01000093,
    E_PS_ACCON_ABNORMAL_SOCVOLTAGE = 0x10000060,
    E_PS_ACCON_ABNORMAL_SOCTEMP = 0x10000051,
    E_PS_ACCON_ABNORMAL_SCRTEMP_HIGH = 0x10000022,
    E_PS_ACCON_ABNORMAL_SCRTEMP_HIGHER = 0x10000043,
    E_PS_ACCON_ABNORMAL_AWAKE = 0x10001070,
    E_PS_GOODBYE_MODE = 0x11000094,
    E_PS_ACCON_NORMAL_POWERON_SCRON = 0x11110010,
    E_PS_ACCON_NORMAL_POWERON_SCROFF = 0x11100030,
    E_PS_ACCON_NORMAL_POWERON_SCROFF_AWAKE = 0x11101010,
    E_PS_ACCON_NORMAL_POWEROFF = 0x11000080,
    E_PS_ACCON_NORMAL_POWEROFF_AWAKE = 0x11001010,
    E_PSTA_DEF_MAX
};

enum ama_changeOfPowerSta_e
{
    E_PS_NO_CHANGE,

    E_ACC_CHANGE_TO_ON,
    E_ACC_CHANGE_TO_OFF,
    E_STATE_CHANGE_TO_NORMAL,
    E_STATE_CHANGE_TO_ABNORMAL,
    E_POWER_CHANGE_TO_ON,
    E_POWER_CHANGE_TO_OFF,
    E_SCR_CHANGE_TO_ON,
    E_SCR_CHANGE_TO_OFF,
};

#endif//AMA_POWERTYPES_H_
